x-healthcheck-defaults: &healthcheck-defaults
  interval: 15s
  timeout: 120s
  retries: 5
  start_period: 60s

services:
  aura-frontend:
    build:
      context: ../../application
      dockerfile: Dockerfile
    container_name: aura-frontend
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/health"]
    restart: unless-stopped
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first

networks:
  default:
    name: aura-network
    external: true
